services:
  - type: web
    name: tomtom-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: TOMTOM_API_KEY
        value: your_actual_api_key_here
